# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               drivojoy.com engineering
description:         drivjoy.com engineering blog
tagline:             drivjoy.com engineering blog
url:                 http://drivojoy.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Rohith Rajan
  url:               https://twitter.com/drivojoy
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/drivojoy/drivojoy.github.io
